import { startMessage, donateMessage } from './constants.js';
import { getRandomPositiveReaction, escapeHtml, splitEmojis } from './helper.js';
import { editStatus, progressText, errorText } from './broadcast.js';
import { logger } from './logger.js';
import { uiText, uiButton } from './font.js';

const TARGETS = { users:['users'], groups:['groups'], channels:['channels'], channel_users:['channel_users'], all:['users','groups','channels','channel_users'] };
const DEFAULT_WELCOME='👋 Welcome {mention} to <b>{group}</b>!\n\nPlease read the group rules and enjoy your stay. ❤️';
const DEFAULT_JOIN='👋 Hello {mention}!\n\nYour request to join <b>{group}</b> has been received.\nPlease wait while an admin reviews it. ✨';
const MUTE_PERMISSIONS={can_send_messages:false,can_send_audios:false,can_send_documents:false,can_send_photos:false,can_send_videos:false,can_send_video_notes:false,can_send_voice_notes:false,can_send_polls:false,can_send_other_messages:false,can_add_web_page_previews:false,can_change_info:false,can_invite_users:false,can_pin_messages:false,can_manage_topics:false};
const UNMUTE_PERMISSIONS={can_send_messages:true,can_send_audios:true,can_send_documents:true,can_send_photos:true,can_send_videos:true,can_send_video_notes:true,can_send_voice_notes:true,can_send_polls:true,can_send_other_messages:true,can_add_web_page_previews:true,can_change_info:false,can_invite_users:false,can_pin_messages:false,can_manage_topics:true};
async function safe(task){try{await task()}catch(e){logger.warn('Storage error:',e.message)}}

export async function onUpdate(data,botApi,Reactions,RestrictedChats,botUsername,RandomLevel,options={}){
 const {store=null,adminIds=[]}=options;
 if(data.chat_join_request){await handleJoinRequest(data.chat_join_request,botApi,store,options);return}
 if(data.chat_member){await handleChatMember(data.chat_member,botApi,store,options);return}
 if(data.callback_query){await onCallback(data.callback_query,botApi,options);return}
 if(data.my_chat_member){const {chat,new_chat_member}=data.my_chat_member;if(store){if(['kicked','left'].includes(new_chat_member?.status))await safe(()=>store.remove(chat.id));else await safe(()=>store.add(chat.id,chat.type,{force:true}));}return}
 if(data.message||data.channel_post){
  const content=data.message||data.channel_post, chatId=content.chat.id, messageId=content.message_id, text=content.text||content.caption||'';
  if(store) await safe(()=>store.add(chatId,content.chat.type));
  const parts=text.trim().split(/\s+/), rawCommand=parts[0]||'', arg=parts.slice(1).join(' '), command=rawCommand.split('@')[0].toLowerCase();
  const isPrivate=content.chat.type==='private',isGroup=['group','supergroup'].includes(content.chat.type),isChannel=content.chat.type==='channel';
  const isGlobalAdmin=!!data.message&&isPrivate&&adminIds.includes(content.from?.id);
  const forwardedChannel=isPrivate?getForwardedChannel(content.reply_to_message):null;
  if(store&&content.from?.id&&isPrivate&&!command.startsWith('/')){const pending=await store.getPending(content.from.id);if(pending){await finishPending(botApi,content,pending,Reactions,store,botUsername,options);return;}}
  if(data.message&&command==='/start') await sendStart(botApi,content,botUsername,options,arg);
  else if(data.message&&command==='/help') await showHelp(botApi,content,botUsername,options);
  else if(data.message&&(command==='/groupsetting'||(command==='/welcome'&&isGroup))) await handleGroupSettingCommand(botApi,content,store,options,forwardedChannel);
  else if(data.message&&command==='/joinsetting'&&isPrivate) await connectAndOpenChannel(botApi,content,store,options,forwardedChannel);
  else if(data.message&&command==='/reactions') await showReactionSettings(botApi,content,Reactions,store,options,forwardedChannel);
  else if(data.message&&command==='/donate') await sendDonate(botApi,chatId,options);
  else if(data.message&&isGroup&&(command==='/reactions_on'||command==='/reactions_off')) await setGroupReactionState(botApi,content,command==='/reactions_on',store);
  else if(data.message&&isPrivate&&forwardedChannel&&(command==='/reactions_on'||command==='/reactions_off')) await setForwardedChannelState(botApi,content,forwardedChannel,command==='/reactions_on',store);
  else if(isGlobalAdmin&&(command==='/stats'||command==='/users')) await sendStats(botApi,chatId,store);
  else if(isGlobalAdmin&&command==='/broadcast') await askBroadcast(botApi,content,arg.toLowerCase(),options);
  else if(isGroup&&content.from?.id&&content.new_chat_members===undefined){
   const custom=store?await store.getReactions(chatId):null,active=custom?.length?custom:Reactions,enabled=store?await store.isReactionsEnabled(chatId):true;
   if(enabled&&active.length&&!RestrictedChats.includes(chatId)&&messageId&&Math.random()<=1-(RandomLevel/10))await botApi.setMessageReaction(chatId,messageId,getRandomPositiveReaction(active));
  }
  else if(isChannel){const custom=store?await store.getReactions(chatId):null,active=custom?.length?custom:Reactions,enabled=store?await store.isReactionsEnabled(chatId):true;if(enabled&&active.length&&!RestrictedChats.includes(chatId)&&messageId)await botApi.setMessageReaction(chatId,messageId,getRandomPositiveReaction(active));}
 }
 if(data.pre_checkout_query){await botApi.answerPreCheckoutQuery(data.pre_checkout_query.id,true);}
}

async function handleChatMember(update,botApi,store){
 const chat=update.chat,oldStatus=update.old_chat_member?.status,member=update.new_chat_member,newStatus=member?.status;
 if(!store||!chat||!['group','supergroup'].includes(chat.type))return;
 await safe(()=>store.add(chat.id,chat.type));
 if(!['member','administrator'].includes(newStatus)||['member','administrator'].includes(oldStatus)||!member?.user||member.user.is_bot)return;
 const s=await store.getGroupSettings(chat.id);
 if(s.required_channel_id){
  let joined=false;try{const m=await botApi.getChatMember(s.required_channel_id,member.user.id);joined=['member','administrator','creator'].includes(m?.status)||(m?.status==='restricted'&&m?.is_member);}catch(e){logger.warn(`Required-channel check failed: ${e.message}`)}
  if(!joined){
   try{await botApi.restrictChatMember(chat.id,member.user.id,MUTE_PERMISSIONS)}catch(e){logger.warn(`Mute failed in ${chat.id}: ${e.message}`)}
   const text=`🔒 Please join the required channel to chat in this group.\n\nOnce you've joined, tap Check & Unmute.`;
   const kb=[[Object.assign(uiButton('📢 JOIN CHANNEL','primary'),{url:s.required_channel_url||'https://t.me/'} )],[Object.assign(uiButton('✅ CHECK & UNMUTE','success'),{callback_data:`reqcheck:${chat.id}`})]];
   try{await botApi.sendMessage(chat.id,`${mention(member.user)} ${uiText(text)}`,kb)}catch(_){ }
   return;
  }
 }
 if(!s.welcome_enabled)return;
 const text=renderTemplate(s.welcome_message||DEFAULT_WELCOME,member.user,chat),keyboard=normalizeButtons(s.welcome_buttons);
 try{if(s.welcome_mode==='only_user')await botApi.sendEphemeralMessage(chat.id,member.user.id,text,keyboard);else await botApi.sendMessage(chat.id,text,keyboard)}catch(e){if(s.welcome_mode==='only_user')try{await botApi.sendMessage(member.user.id,text,keyboard)}catch(_){} }
}

async function handleJoinRequest(request,botApi,store){
 if(!store)return;const chat=request.chat,user=request.from;if(!chat?.id||!user?.id)return;
 await safe(()=>store.add(user.id,'private'));await safe(()=>store.addChannelRequestUser?.(user.id));await safe(()=>store.add(chat.id,chat.type));
 const s=await store.getGroupSettings(chat.id);if(!s.join_enabled)return;
 const recipient=request.user_chat_id||user.id,text=renderTemplate(s.join_message||DEFAULT_JOIN,user,chat),keyboard=normalizeButtons(s.join_buttons);
 try{await botApi.sendMessage(recipient,text,keyboard)}catch(e){logger.warn(`Join request notification failed: ${e.message}`)}
 if(s.join_mode==='auto_accept')try{await botApi.approveChatJoinRequest(chat.id,user.id);try{await botApi.sendMessage(recipient,renderTemplate('<b>✅ Your request has been accepted.</b>\nWelcome to {group}! 🎉',user,chat),keyboard)}catch(_){}}catch(e){logger.warn(`Auto-accept failed: ${e.message}`)}
}
function renderTemplate(text,user,chat){const name=escapeHtml([user?.first_name,user?.last_name].filter(Boolean).join(' ')||'there'),username=user?.username?`@${escapeHtml(user.username)}`:name,mention=`<a href="tg://user?id=${user?.id}">${name}</a>`,group=escapeHtml(chat?.title||'this chat');return String(text).replaceAll('{name}',name).replaceAll('{username}',username).replaceAll('{mention}',mention).replaceAll('{group}',group)}
function mention(user){return `<a href="tg://user?id=${user.id}">${escapeHtml(user.first_name||'User')}</a>`}
function normalizeButtons(buttons){if(!Array.isArray(buttons))return null;const rows=[];for(const item of buttons){if(Array.isArray(item)){const r=item.filter(x=>x?.text&&x?.url).slice(0,4).map(x=>({text:x.text,url:x.url,...(x.style?{style:x.style}:{})}));if(r.length)rows.push(r)}else if(item?.text&&item?.url)rows.push([{text:item.text,url:item.url,...(item.style?{style:item.style}:{})}]);}return rows.length?rows:null}
function parseButtons(value){const lines=value.split('\n').map(x=>x.trim()).filter(Boolean).slice(0,16),rows=[];for(const line of lines){const parts=line.split('|').map(x=>x.trim());if(!parts[0]||!/^https?:\/\//i.test(parts[1]||''))continue;const style=['primary','success','danger'].includes(parts[2])?parts[2]:'primary';const row=Number(parts[3]);rows[row-1]=(rows[row-1]||[]).concat({text:parts[0],url:parts[1],style});}return rows.filter(Boolean).map(r=>r.slice(0,4)).slice(0,8)}
function getForwardedChannel(message){const o=message?.forward_origin;return o?.type==='channel'&&o.chat?.id?o.chat:null}
async function verifyAdmin(api,chatId,userId){try{return ['creator','administrator'].includes((await api.getChatMember(chatId,userId))?.status)}catch{return false}}
async function verifyGroupAdmin(api,c){return verifyAdmin(api,c.chat.id,c.from?.id)}
async function notConfigured(api,id){return api.sendMessage(id,uiText('⚠️ Database is not configured.'))}

async function handleGroupSettingCommand(api,content,store,options,forwardedChannel){
 if(!store)return notConfigured(api,content.chat.id);
 if(['group','supergroup'].includes(content.chat.type)){
  if(!(await verifyGroupAdmin(api,content)))return api.sendEphemeralMessage(content.chat.id,content.from?.id,uiText('⚠️ Only group admins can use /groupsetting.'));
  await store.connect(content.from.id,content.chat.id,'group',content.chat.title||'Group');
  const url=`https://t.me/${options.botUsername}?start=group_${content.chat.id}`;
  const text=uiText('⚙️ This group is connected. Open the private settings panel to manage it without leaving settings here.');
  try{return await api.sendEphemeralMessage(content.chat.id,content.from.id,text,[[Object.assign(uiButton('⚙️ OPEN GROUP SETTINGS','primary'),{url})]])}catch{return api.sendMessage(content.chat.id,text,[[Object.assign(uiButton('⚙️ OPEN GROUP SETTINGS','primary'),{url})]])}
 }
 if(content.chat.type==='private'){
  if(forwardedChannel)return connectAndOpenChannel(api,content,store,options,forwardedChannel);
  return showConnections(api,content.chat.id,content.from.id,store,options);
 }
 return api.sendMessage(content.chat.id,uiText('⚠️ Use /groupsetting in a group or in my private chat.'));
}

async function showConnections(api,chatId,userId,store,options){
 const list=await store.connections(userId),groups=list.filter(x=>x.kind==='group'),channels=list.filter(x=>x.kind==='channel');
 if(!list.length)return api.sendMessage(chatId,uiText('⚙️ You have no connected groups or channels yet.\n\nTo connect a group, add me as an admin and send /groupsetting in that group.\nTo connect a channel, add me as an admin, forward a channel post here and use /groupsetting.'));
 const groupRows=groups.slice(0,20).map(x=>[Object.assign(uiButton(`👥 ${x.title||`Group ${x.chat_id}`}`,'primary'),{callback_data:`open:group:${x.chat_id}`})]);
 const channelRows=channels.slice(0,20).map(x=>[Object.assign(uiButton(`📢 ${x.title||`Channel ${x.chat_id}`}`,'primary'),{callback_data:`open:channel:${x.chat_id}`})]);
 const buttons=[];
 if(groups.length&&channels.length){
   buttons.push([Object.assign(uiButton('👥 GROUPS','primary'),{callback_data:'pick:group'}),Object.assign(uiButton('📢 CHANNELS','primary'),{callback_data:'pick:channel'})]);
 } else if(groups.length) buttons.push(...groupRows);
 else buttons.push(...channelRows);
 buttons.push([Object.assign(uiButton('➕ CONNECT GROUP','success'),{callback_data:'connect:group'}),Object.assign(uiButton('➕ CONNECT CHANNEL','success'),{callback_data:'connect:channel'})]);
 buttons.push([Object.assign(uiButton('↩️ BACK','primary'),{callback_data:'back'})]);
 return api.sendMessage(chatId,uiText(`⚙️ CONNECTED TARGETS\n\n👥 Groups: ${groups.length}\n📢 Channels: ${channels.length}\n\nSelect a target to open its settings.`),buttons);
}
async function connectAndOpenChannel(api,content,store,options,forwarded){if(!forwarded)return api.sendMessage(content.chat.id,uiText('📢 Forward a post from the channel here, then send /groupsetting.'));if(!(await verifyAdmin(api,forwarded.id,content.from.id)))return api.sendMessage(content.chat.id,uiText('⚠️ You must be a channel admin and the bot must be an admin in that channel.'));await store.connect(content.from.id,forwarded.id,'channel',forwarded.title||'Channel');return showChannelSettings(api,content.chat.id,content.from.id,forwarded.id,store,options)}

async function showGroupSettings(api,chatId,userId,targetId,store,options,editMessageId=null){const s=await store.getGroupSettings(targetId);const text=uiText(`⚙️ GROUP SETTINGS\n\n👋 Welcome: ${s.welcome_enabled?'🟢 ON':'🔴 OFF'}\n❤️ Reactions: ${s.reactions_enabled?'🟢 ON':'🔴 OFF'}\n🔐 Required Channel: ${s.required_channel_id?'🟢 SET':'🔴 OFF'}`);const kb=[ [Object.assign(uiButton(s.welcome_enabled?'👋 WELCOME ON':'👋 WELCOME OFF',s.welcome_enabled?'success':'danger'),{callback_data:`gs:welcome:${targetId}:${s.welcome_enabled?0:1}`}),Object.assign(uiButton('📝 MESSAGE','primary'),{callback_data:`input:wmsg:${targetId}`})],[Object.assign(uiButton('👤 ONLY USER','primary'),{callback_data:`gs:wmode:${targetId}:only_user`}),Object.assign(uiButton('👥 GROUP','primary'),{callback_data:`gs:wmode:${targetId}:group`})],[Object.assign(uiButton('🔘 BUTTONS','primary'),{callback_data:`buttons:welcome:${targetId}`})],[Object.assign(uiButton(s.reactions_enabled?'❤️ REACTIONS ON':'❤️ REACTIONS OFF',s.reactions_enabled?'success':'danger'),{callback_data:`gs:react:${targetId}:${s.reactions_enabled?0:1}`}),Object.assign(uiButton('✏️ REACTIONS','primary'),{callback_data:`input:reactions:${targetId}`})],[Object.assign(uiButton(s.required_channel_id?'🔐 CHANNEL ON':'🔐 REQUIRE CHANNEL',s.required_channel_id?'success':'primary'),{callback_data:`reqset:${targetId}`})],[Object.assign(uiButton('👁 PREVIEW','success'),{callback_data:`preview:welcome:${targetId}`}),Object.assign(uiButton('🔌 DISCONNECT','danger'),{callback_data:`disconnect:group:${targetId}`})],[Object.assign(uiButton('↩️ CONNECTIONS','primary'),{callback_data:'connections'})] ];if(editMessageId)return api.editMessageText(chatId,editMessageId,text,kb);return api.sendMessage(chatId,text,kb)}
async function showChannelSettings(api,chatId,userId,targetId,store,options,editMessageId=null){const s=await store.getGroupSettings(targetId);const text=uiText(`📢 CHANNEL SETTINGS\n\n❤️ Reactions: ${s.reactions_enabled?'🟢 ON':'🔴 OFF'}\n🛡️ Join Requests: ${s.join_enabled?'🟢 ON':'🔴 OFF'}\nMode: ${s.join_mode==='auto_accept'?'✅ AUTO ACCEPT':'🔔 NOTIFY ONLY'}`);const kb=[[Object.assign(uiButton(s.reactions_enabled?'❤️ REACTIONS ON':'❤️ REACTIONS OFF',s.reactions_enabled?'success':'danger'),{callback_data:`cs:react:${targetId}:${s.reactions_enabled?0:1}`})],[Object.assign(uiButton(s.join_enabled?'🛡️ REQUESTS ON':'🛡️ REQUESTS OFF',s.join_enabled?'success':'danger'),{callback_data:`cs:join:${targetId}:${s.join_enabled?0:1}`}),Object.assign(uiButton(s.join_mode==='auto_accept'?'🔔 NOTIFY ONLY':'✅ AUTO ACCEPT','primary'),{callback_data:`cs:mode:${targetId}:${s.join_mode==='auto_accept'?'notify':'auto_accept'}`})],[Object.assign(uiButton('📝 REQUEST MESSAGE','primary'),{callback_data:`input:jmsg:${targetId}`})],[Object.assign(uiButton('🔘 REQUEST BUTTONS','primary'),{callback_data:`buttons:join:${targetId}`})],[Object.assign(uiButton('👁 PREVIEW','success'),{callback_data:`preview:join:${targetId}`}),Object.assign(uiButton('🔌 DISCONNECT','danger'),{callback_data:`disconnect:channel:${targetId}`})],[Object.assign(uiButton('↩️ CONNECTIONS','primary'),{callback_data:'connections'})]];if(editMessageId)return api.editMessageText(chatId,editMessageId,text,kb);return api.sendMessage(chatId,text,kb)}

async function beginInput(api,q,store,mode,targetId,prompt,payload={}){await store.setPending(q.from.id,targetId,mode,{...payload,panel_chat_id:q.message.chat.id,panel_message_id:q.message.message_id});await api.answerCallbackQuery(q.id);return api.editMessageText(q.message.chat.id,q.message.message_id,uiText(prompt),[[Object.assign(uiButton('❌ CANCEL','danger'),{callback_data:'inputcancel'})]])}
async function finishPending(api,content,pending,Reactions,store,botUsername,options){const value=(content.text||'').trim(),p=pending.payload||{};await store.clearPending(content.from.id);if(!value)return api.sendMessage(content.chat.id,uiText('⚠️ Input cannot be empty.'));
 if(pending.mode==='wmsg'||pending.mode==='jmsg'){await store.updateGroupSettings(pending.chatId,{[pending.mode==='wmsg'?'welcome_message':'join_message']:value});return pendingPanel(api,content.from.id,p, pending.chatId,pending.mode==='wmsg'?'group':'channel',store,options)}
 if(pending.mode==='reactions'){const r=splitEmojis(value).slice(0,20);if(!r.length)return api.sendMessage(content.chat.id,uiText('⚠️ No valid emoji reactions found.'));await store.setReactions(pending.chatId,r);return pendingPanel(api,content.from.id,p,pending.chatId,'group',store,options)}
 if(pending.mode==='reqchannel'){const parts=value.split('|').map(x=>x.trim());const id=Number(parts[0]);const url=parts[1]||'';if(!id||!/^https?:\/\//i.test(url))return api.sendMessage(content.chat.id,uiText('⚠️ Format: channel numeric ID | https://t.me/...'));try{const meInfo=await api.getMe();const me=await api.getChatMember(id,meInfo.id);if(!['administrator','creator'].includes(me?.status))return api.sendMessage(content.chat.id,uiText('⚠️ I must be an admin in that channel before it can be used.'))}catch{return api.sendMessage(content.chat.id,uiText('⚠️ I could not verify that channel. Make me an admin first.'))}await store.updateGroupSettings(pending.chatId,{required_channel_id:id,required_channel_url:url});return pendingPanel(api,content.from.id,p,pending.chatId,'group',store,options)}
 if(pending.mode==='buttonadd'||pending.mode==='buttondelete'){const s=await store.getGroupSettings(pending.chatId);const key=pending.mode.startsWith('button')?(pending.payload?.target==='join'?'join_buttons':'welcome_buttons'):'';const parsed= pending.mode==='buttonadd'?parseButtons(value):[];if(pending.mode==='buttonadd'){const existing=s[key]||[];await store.updateGroupSettings(pending.chatId,{[key]:existing.concat(parsed).slice(0,8)});}return pendingPanel(api,content.from.id,p,pending.chatId,pending.payload?.target==='join'?'channel':'group',store,options)}
}
async function pendingPanel(api,userId,p,targetId,kind,store,options){const panelId=p.panel_message_id,chatId=p.panel_chat_id;if(!panelId)return kind==='group'?showGroupSettings(api,userId,userId,targetId,store,options):showChannelSettings(api,userId,userId,targetId,store,options);return kind==='group'?showGroupSettings(api,chatId,userId,targetId,store,options,panelId):showChannelSettings(api,chatId,userId,targetId,store,options,panelId)}

async function sendStart(api,content,botUsername,options,arg=''){if(arg.startsWith('group_')){const id=Number(arg.slice(6));if(id&&await verifyAdmin(api,id,content.from.id)&&options.store){const kind=await options.store.kindForId?.(id);const chat=await api.getChat(id).catch(()=>({}));await options.store.connect(content.from.id,id,'group',chat.title||`Group ${id}`);return showGroupSettings(api,content.chat.id,content.from.id,id,options.store,options)}}const name=escapeHtml(content.from?.first_name||'UserName'),text=startMessage.replace('UserName',name),updates=options.updatesUrl||`https://t.me/${botUsername}`,support=options.supportUrl||`https://t.me/${botUsername}`;const kb=[[Object.assign(uiButton('⇆ ADD ME TO YOUR CHANNELS ⇆','success'),{url:`https://t.me/${botUsername}?startchannel=botstart`})],[Object.assign(uiButton('⇆ ADD ME TO YOUR GROUPS ⇆','success'),{url:`https://t.me/${botUsername}?startgroup=botstart`})],[Object.assign(uiButton('❓ HELP','primary'),{callback_data:'help'}),Object.assign(uiButton('⚙️ SETTINGS','primary'),{callback_data:'settings'})],[Object.assign(uiButton('• UPDATES •','primary'),{url:updates}),Object.assign(uiButton('• SUPPORT •','primary'),{url:support})],[Object.assign(uiButton('💰 DONATION','success'),{callback_data:'donate'})]];if(options.startAnimation)try{return await api.sendAnimation(content.chat.id,options.startAnimation,text,kb)}catch(_){}return api.sendMessage(content.chat.id,text,kb)}
async function showHelp(api,content,botUsername,options){const text=uiText('❖ HELP CENTER\n\n➜ AUTO REACTION\nAutomatically reacts to eligible group and channel messages.\n\n➜ GROUP SETTINGS\nUse /groupsetting in your group as an admin.\n\n➜ WELCOME\nCustom message, inline buttons and Only User / Group mode.\n\n➜ JOIN REQUIREMENT\nRequire users to join a channel before chatting.\n\n➜ JOIN REQUESTS\nCustom notification, buttons and Auto Accept / Notify Only.');const kb=[[Object.assign(uiButton('💬 SUPPORT','primary'),{url:options.supportUrl||`https://t.me/${botUsername}`}),Object.assign(uiButton('💰 DONATION','success'),{callback_data:'donate'})],[Object.assign(uiButton('◀️ BACK','primary'),{callback_data:'back'})]];return api.sendMessage(content.chat.id,text,kb)}
async function showWelcomeEdited(api,q,botUsername,options){const name=escapeHtml(q.from?.first_name||'there'),text=startMessage.replace('UserName',name),kb=[[Object.assign(uiButton('⇆ ADD ME TO YOUR CHANNELS ⇆','success'),{url:`https://t.me/${botUsername}?startchannel=botstart`})],[Object.assign(uiButton('⇆ ADD ME TO YOUR GROUPS ⇆','success'),{url:`https://t.me/${botUsername}?startgroup=botstart`})],[Object.assign(uiButton('❓ HELP','primary'),{callback_data:'help'}),Object.assign(uiButton('⚙️ SETTINGS','primary'),{callback_data:'settings'})],[Object.assign(uiButton('• UPDATES •','primary'),{url:options.updatesUrl||`https://t.me/${botUsername}`}),Object.assign(uiButton('• SUPPORT •','primary'),{url:options.supportUrl||`https://t.me/${botUsername}`})],[Object.assign(uiButton('💰 DONATION','success'),{callback_data:'donate'})]];return api.editMessageText(q.message.chat.id,q.message.message_id,text,kb)}
async function sendDonate(api,id,options){if(options.donateAnimation)try{await api.sendAnimation(id,options.donateAnimation,uiText('🙏 Support Auto Reaction Bot ✨'))}catch(_){}return api.sendInvoice(id,uiText('Donate to Auto Reactions Bot ✨'),uiText(donateMessage),'{}', '', 'donate','XTR',[{label:'Pay ⭐️5',amount:5}])}
async function sendStats(api,id,store){const c=await store.counts(),r=store.channelRequestCount?await store.channelRequestCount():0;return api.sendMessage(id,uiText(`📊 BOT STATS\n\n👤 Users: ${c.users}\n👥 Groups: ${c.groups}\n📢 Channels: ${c.channels}\n📨 Channel Request Users: ${r}\n\n🧮 Total Chats: ${c.users+c.groups+c.channels}`))}
async function askBroadcast(api,content,target,options){const {store,enqueueBroadcast}=options,reply=content.reply_to_message;if(!store||!enqueueBroadcast)return notConfigured(api,content.chat.id);if(!reply)return api.sendMessage(content.chat.id,uiText('📢 Reply to the message you want to broadcast with /broadcast.'));const t=TARGETS[target]?target:'users',c=await store.counts(),requestCount=t==='channel_users'?(await store.channelRequestCount?.()||0):0,total=t==='channel_users'?requestCount:TARGETS[t].reduce((n,k)=>n+(c[k]||0),0);if(!total)return api.sendMessage(content.chat.id,uiText('⚠️ No recipients found.'));const base=`bc:${t}:${content.chat.id}:${reply.message_id}`;return api.sendMessage(content.chat.id,uiText(`📢 Broadcast to ${total} ${t=== 'all'?'chats':t}.\n\n1️⃣ Choose delivery mode:`),[[Object.assign(uiButton('📤 COPY','primary'),{callback_data:`${base}:copy`}),Object.assign(uiButton('↪️ FORWARD','primary'),{callback_data:`${base}:forward`})],[Object.assign(uiButton('❌ CANCEL','danger'),{callback_data:'bcx'})]])}

async function showReactionSettings(api,content,defaults,store,options,forwarded){if(!store)return notConfigured(api,content.chat.id);let id=content.chat.id,title=content.chat.title||'this chat';if(content.chat.type==='private'){if(!forwarded)return api.sendMessage(content.chat.id,uiText('⚙️ Forward a channel post here and use /reactions.'));id=forwarded.id;title=forwarded.title||'Channel';if(!(await verifyAdmin(api,id,content.from.id)))return api.sendMessage(content.chat.id,uiText('⚠️ Channel admins only.'))}else if(!['group','supergroup','channel'].includes(content.chat.type)||!(await verifyAdmin(api,id,content.from.id)))return api.sendMessage(content.chat.id,uiText('⚠️ Admins only.'));const on=await store.isReactionsEnabled(id),r=await store.getReactions(id);return api.sendMessage(content.chat.id,uiText(`⚙️ REACTION SETTINGS — ${title}\n\nStatus: ${on?'🟢 ON':'🔴 OFF'}\nReactions: ${(r||defaults).join(' ')}`),[[Object.assign(uiButton(on?'🔴 TURN OFF':'🟢 TURN ON',on?'danger':'success'),{callback_data:`rs:${on?'off':'on'}:${id}`}),Object.assign(uiButton('✏️ CUSTOM','primary'),{callback_data:`input:reactions:${id}`})],[Object.assign(uiButton('🔄 RESET','primary'),{callback_data:`rs:reset:${id}`})]])}
async function setGroupReactionState(api,c,en,store){if(!(await verifyGroupAdmin(api,c)))return api.sendEphemeralMessage(c.chat.id,c.from.id,uiText('⚠️ Only group admins can change reaction settings.'));await store.setReactionsEnabled(c.chat.id,en);return api.sendEphemeralMessage(c.chat.id,c.from.id,uiText(en?'🟢 Auto reactions enabled.':'🔴 Auto reactions disabled.'))}
async function setForwardedChannelState(api,c,ch,en,store){if(!(await verifyAdmin(api,ch.id,c.from.id)))return api.sendMessage(c.chat.id,uiText('⚠️ Channel admins only.'));await store.setReactionsEnabled(ch.id,en);return api.sendMessage(c.chat.id,uiText(`${en?'🟢':'🔴'} Reactions ${en?'enabled':'disabled'} for ${ch.title||'the channel'}.`))}

async function onCallback(q,api,options){const {store=null,adminIds=[],enqueueBroadcast=null}=options,d=q.data||'',chatId=q.message?.chat?.id,msgId=q.message?.message_id;
 if(d==='donate'){await api.answerCallbackQuery(q.id);return sendDonate(api,chatId,options)}
 if(d==='help'){await api.answerCallbackQuery(q.id);try{await api.deleteMessage(chatId,msgId)}catch(_){}return showHelp(api,{chat:{id:chatId},from:q.from},options.botUsername,options)}
 if(d==='back'){await api.answerCallbackQuery(q.id);return showWelcomeEdited(api,q,options.botUsername,options)}
 if(d==='settings'||d==='connections'){await api.answerCallbackQuery(q.id);return showConnections(api,chatId,q.from.id,store,options)}
 if(d==='inputcancel'){await store.clearPending(q.from.id);await api.answerCallbackQuery(q.id);return showConnections(api,chatId,q.from.id,store,options)}
 if(d==='connect:channel'){await api.answerCallbackQuery(q.id);return api.sendMessage(chatId,uiText('📢 Forward a post from the channel here, then send /groupsetting.'))}
 if(d==='connect:group'){await api.answerCallbackQuery(q.id);return api.sendMessage(chatId,uiText(`👥 Add me to your group as an admin, then send /groupsetting there.\n\nhttps://t.me/${options.botUsername}?startgroup=botstart`))}
 if(d.startsWith('pick:')){const kind=d.split(':')[1],list=await store.connections(q.from.id,kind);await api.answerCallbackQuery(q.id);return api.editMessageText(chatId,msgId,uiText(`⚙️ SELECT ${kind.toUpperCase()}`),list.slice(0,20).map(x=>[Object.assign(uiButton(x.title||`${kind} ${x.chat_id}`,'primary'),{callback_data:`open:${kind}:${x.chat_id}`})]).concat([[Object.assign(uiButton('↩️ BACK','primary'),{callback_data:'connections'})]]))}
 if(d.startsWith('open:')){const [,kind,id]=d.split(':');if(!(await verifyAdmin(api,Number(id),q.from.id)))return api.answerCallbackQuery(q.id,'You are no longer an admin.',true);await api.answerCallbackQuery(q.id);return kind==='group'?showGroupSettings(api,chatId,q.from.id,Number(id),store,options,msgId):showChannelSettings(api,chatId,q.from.id,Number(id),store,options,msgId)}
 if(d.startsWith('disconnect:')){const [,kind,id]=d.split(':');await store.disconnect(q.from.id,Number(id));await api.answerCallbackQuery(q.id,'Disconnected');return showConnections(api,chatId,q.from.id,store,options)}
 if(d.startsWith('gs:')){const [,a,idRaw,v]=d.split(':'),id=Number(idRaw);if(!(await verifyAdmin(api,id,q.from.id)))return api.answerCallbackQuery(q.id,'Admins only',true);if(a==='welcome')await store.updateGroupSettings(id,{welcome_enabled:v==='1'});else if(a==='wmode')await store.updateGroupSettings(id,{welcome_mode:v==='only_user'?'only_user':'group'});else if(a==='react')await store.setReactionsEnabled(id,v==='1');else {await api.answerCallbackQuery(q.id);return showGroupSettings(api,chatId,q.from.id,id,store,options,msgId)}await api.answerCallbackQuery(q.id);return showGroupSettings(api,chatId,q.from.id,id,store,options,msgId)}
 if(d.startsWith('cs:')){const [,a,idRaw,v]=d.split(':'),id=Number(idRaw);if(!(await verifyAdmin(api,id,q.from.id)))return api.answerCallbackQuery(q.id,'Admins only',true);if(a==='react')await store.setReactionsEnabled(id,v==='1');else if(a==='join')await store.updateGroupSettings(id,{join_enabled:v==='1'});else if(a==='mode')await store.updateGroupSettings(id,{join_mode:v==='auto_accept'?'auto_accept':'notify'});await api.answerCallbackQuery(q.id);return showChannelSettings(api,chatId,q.from.id,id,store,options,msgId)}
 if(d.startsWith('input:')){const [,mode,idRaw]=d.split(':'),id=Number(idRaw);if(!(await verifyAdmin(api,id,q.from.id)))return api.answerCallbackQuery(q.id,'Admins only',true);const prompt={wmsg:'📝 Send the new welcome message.\n\nVariables: {name} {username} {mention} {group}',jmsg:'📝 Send the new join-request message.\n\nVariables: {name} {username} {mention} {group}',reactions:'✏️ Send 1–20 emoji reactions.'}[mode]||'📝 Send the new value.';return beginInput(api,q,store,mode,id,prompt)}
 if(d.startsWith('reqset:')){const id=Number(d.split(':')[1]);if(!(await verifyAdmin(api,id,q.from.id)))return api.answerCallbackQuery(q.id,'Admins only',true);const s=await store.getGroupSettings(id);await api.answerCallbackQuery(q.id);return api.editMessageText(chatId,msgId,uiText(`🔐 REQUIRED CHANNEL\n\nStatus: ${s.required_channel_id?'🟢 SET':'🔴 NOT SET'}\n\nThe bot must be an admin in the required channel.`),[[Object.assign(uiButton('📝 SET CHANNEL','primary'),{callback_data:`input:reqchannel:${id}`})],[Object.assign(uiButton('🗑 REMOVE','danger'),{callback_data:`reqremove:${id}`})],[Object.assign(uiButton('↩️ BACK','primary'),{callback_data:`open:group:${id}`})]])}
 if(d.startsWith('reqremove:')){const id=Number(d.split(':')[1]);await store.updateGroupSettings(id,{required_channel_id:null,required_channel_url:''});await api.answerCallbackQuery(q.id);return showGroupSettings(api,chatId,q.from.id,id,store,options,msgId)}
 if(d.startsWith('reqcheck:')){const gid=Number(d.split(':')[1]),uid=q.from.id,s=await store.getGroupSettings(gid);let ok=false;try{const m=await api.getChatMember(s.required_channel_id,uid);ok=['member','administrator','creator'].includes(m?.status)||(m?.status==='restricted'&&m?.is_member)}catch(_){}if(!ok){await api.answerCallbackQuery(q.id,'Please join the channel first.',true);return}try{await api.restrictChatMember(gid,uid,UNMUTE_PERMISSIONS)}catch(e){await api.answerCallbackQuery(q.id,'I cannot unmute you. Check my admin permissions.',true);return}await api.answerCallbackQuery(q.id,'Verified!');try{await api.deleteMessage(chatId,msgId)}catch(_){}return api.sendMessage(gid,uiText(`✅ ${q.from.first_name||'You'} has joined the required channel and can now chat.`))}
 if(d.startsWith('preview:')){const [,type,idRaw]=d.split(':'),id=Number(idRaw),s=await store.getGroupSettings(id);await api.answerCallbackQuery(q.id);return api.sendMessage(chatId,type==='welcome'?renderTemplate(s.welcome_message||DEFAULT_WELCOME,q.from,{title:'Preview Group'}):renderTemplate(s.join_message||DEFAULT_JOIN,q.from,{title:'Preview Channel'}),normalizeButtons(type==='welcome'?s.welcome_buttons:s.join_buttons))}
 if(d.startsWith('buttons:')){const [,target]=d.split(':'),id=Number(d.split(':')[2]);if(!(await verifyAdmin(api,id,q.from.id)))return api.answerCallbackQuery(q.id,'Admins only',true);await api.answerCallbackQuery(q.id);return api.editMessageText(chatId,msgId,uiText(`🔘 ${target.toUpperCase()} BUTTONS`),[[Object.assign(uiButton('➕ ADD BUTTON','success'),{callback_data:`buttonadd:${target}:${id}`})],[Object.assign(uiButton('🗑 DELETE BUTTON','danger'),{callback_data:`buttondelete:${target}:${id}`})],[Object.assign(uiButton('👁 PREVIEW','primary'),{callback_data:`preview:${target==='join'?'join':'welcome'}:${id}`})],[Object.assign(uiButton('↩️ BACK','primary'),{callback_data:`open:${target==='join'?'channel':'group'}:${id}`})]])}
 if(d.startsWith('buttonadd:')){const [,target,idRaw]=d.split(':'),id=Number(idRaw);const mode='buttonadd';return beginInput(api,q,store,mode,id,'➕ Send button(s), one per line:\nButton Name | https://example.com | primary | row\n\nUse the same row number for buttons that should share one row.',{target});}
 if(d.startsWith('buttondelete:')){const [,target,idRaw]=d.split(':'),id=Number(idRaw),s=await store.getGroupSettings(id),buttons=target==='join'?s.join_buttons:s.welcome_buttons;await api.answerCallbackQuery(q.id);if(!buttons.length)return api.editMessageText(chatId,msgId,uiText('🗑️ No buttons configured.'),[[Object.assign(uiButton('↩️ BACK','primary'),{callback_data:`buttons:${target}:${id}`})]]);return api.editMessageText(chatId,msgId,uiText('🗑️ Choose what to delete.'),[[Object.assign(uiButton('🗑️ DELETE ALL','danger'),{callback_data:`delall:${target}:${id}`})],[Object.assign(uiButton('🗑️ DELETE ONE','primary'),{callback_data:`delone:${target}:${id}`})],[Object.assign(uiButton('❌ CANCEL','primary'),{callback_data:`buttons:${target}:${id}`})]])}
 if(d.startsWith('delall:')){const [,target,idRaw]=d.split(':'),id=Number(idRaw);await store.updateGroupSettings(id,{[target==='join'?'join_buttons':'welcome_buttons']:[]});await api.answerCallbackQuery(q.id,'All buttons deleted');return target==='join'?showChannelSettings(api,chatId,q.from.id,id,store,options,msgId):showGroupSettings(api,chatId,q.from.id,id,store,options,msgId)}
 if(d.startsWith('delone:')){const [,target,idRaw]=d.split(':'),id=Number(idRaw),s=await store.getGroupSettings(id),b=target==='join'?s.join_buttons:s.welcome_buttons;await api.answerCallbackQuery(q.id);return api.editMessageText(chatId,msgId,uiText('🗑️ Select one button to delete.'),b.flatMap((row,ri)=>row.map((x,ci)=>[Object.assign(uiButton(x.text,'danger'),{callback_data:`del:${target}:${id}:${ri}:${ci}`})])).concat([[Object.assign(uiButton('↩️ BACK','primary'),{callback_data:`buttons:${target}:${id}`})]]))}
 if(d.startsWith('del:')){const [,target,idRaw,ri,ci]=d.split(':'),id=Number(idRaw),s=await store.getGroupSettings(id),key=target==='join'?'join_buttons':'welcome_buttons',b=s[key]||[];if(b[Number(ri)])b[Number(ri)].splice(Number(ci),1);await store.updateGroupSettings(id,{[key]:b.filter(r=>r.length)});await api.answerCallbackQuery(q.id,'Button deleted');return target==='join'?showChannelSettings(api,chatId,q.from.id,id,store,options,msgId):showGroupSettings(api,chatId,q.from.id,id,store,options,msgId)}
 if(d.startsWith('bc:'))return broadcastCallback(q,api,options);
 if(d==='bcx'){await api.answerCallbackQuery(q.id);return api.editMessageText(chatId,msgId,uiText('❌ Broadcast cancelled.'))}
 await api.answerCallbackQuery(q.id);
}
async function broadcastCallback(q,api,options){const {store,enqueueBroadcast}=options;if(!options.adminIds.includes(q.from.id))return api.answerCallbackQuery(q.id,'Not allowed',true);const p=q.data.split(':'),target=p[1],fromChatId=Number(p[2]),sourceMessageId=Number(p[3]),mode=p[4],pin=p[5];if(p.length===5){await api.answerCallbackQuery(q.id);return api.editMessageText(q.message.chat.id,q.message.message_id,uiText(`📢 ${mode.toUpperCase()} selected.\n\n2️⃣ Pin the broadcast?`),[[Object.assign(uiButton('📌 PIN','success'),{callback_data:`${q.data}:1`}),Object.assign(uiButton('🚫 WITHOUT PIN','primary'),{callback_data:`${q.data}:0`})],[Object.assign(uiButton('❌ CANCEL','danger'),{callback_data:'bcx'})]])}const c=await store.counts(),total=target==='channel_users'?await store.channelRequestCount():TARGETS[target].reduce((n,k)=>n+(c[k]||0),0),job={kinds:target==='channel_users'?['channel_users']:TARGETS[target],channelUsers:target==='channel_users',fromChatId,messageId:sourceMessageId,statusChatId:q.message.chat.id,statusMessageId:q.message.message_id,afterId:Number.MIN_SAFE_INTEGER,total,sent:0,failed:0,removed:0,startedAt:Date.now(),mode,pin:pin==='1'};await api.answerCallbackQuery(q.id);await editStatus(api,job,progressText(job));try{await enqueueBroadcast(job)}catch(e){await editStatus(api,job,errorText(job,e))}}
